### ISSUE TITLE
 Unhandled exception rendering component: Cannot set properties of null (setting 'innerHTML')

### ISSUE THREAD

**Issue by HuaFangYun** [ant-design-blazor/ant-design-charts-blazor#135]
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot set properties of null (setting 'innerHTML')
TypeError: Cannot set properties of null (setting 'innerHTML')
    at Object.create (https://localhost:5002/_content/AntDesign.Charts/ant-design-charts-blazor.js:7:30)
    at https://localhost:5002/_framework/blazor.server.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:5002/_framework/blazor.server.js:1:3201)
    at Xt._invokeClientMethod (https://localhost:5002/_framework/blazor.server.js:1:61001)
    at Xt._processIncomingData (https://localhost:5002/_framework/blazor.server.js:1:58476)
    at Xt.connection.onreceive (https://localhost:5002/_framework/blazor.server.js:1:52117)
    at s.onmessage (https://localhost:5002/_framework/blazor.server.js:1:80262)
      Microsoft.JSInterop.JSException: Cannot set properties of null (setting 'innerHTML')
TypeError: Cannot set properties of null (setting 'innerHTML')
    at Object.create (https://localhost:5002/_content/AntDesign.Charts/ant-design-charts-blazor.js:7:30)
    at https://localhost:5002/_framework/blazor.server.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:5002/_framework/blazor.server.js:1:3201)
    at Xt._invokeClientMethod (https://localhost:5002/_framework/blazor.server.js:1:61001)
    at Xt._processIncomingData (https://localhost:5002/_framework/blazor.server.js:1:58476)
    at Xt.connection.onreceive (https://localhost:5002/_framework/blazor.server.js:1:52117)
    at s.onmessage (https://localhost:5002/_framework/blazor.server.js:1:80262)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at AntDesign.Charts.ChartComponentBase`1.Create()
         at AntDesign.Charts.ChartComponentBase`1.UpdateChart(Object csConfig, Object csOtherConfig, String jsonConfig, String jsConfig, Boolean all, Object csData)
         at AntDesign.Charts.ChartComponentBase`1.ChangeData(Object data, Boolean all)

**Comment by HuaFangYun** [comment]
5.0 OK
5.1 Error
The latest code local running program reported an error

**Comment by Gareth064** [comment]
I get this error if I navigate away from a page before a chart is finished rendering. How can we stop this?

**Comment by ElderJames** [comment]
@Gareth064 I will take a look
