### ISSUE TITLE
使用最新AntDesign.Charts（0.5.6）的报错Maximum call stack size exceeded RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by xgysigned** [ant-design-blazor/ant-design-charts-blazor#153]
tartTime 12/13/2024 10:06:56
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at proccessObject (http://localhost:6351/_content/AntDesign.Charts/ant-design-charts-blazor.js:120:24)
    at removeNullItem (http://localhost:6351/_content/AntDesign.Charts/ant-design-charts-blazor.js:137:9)
    at processArray (http://localhost:6351/_content/AntDesign.Charts/ant-design-charts-blazor.js:115:45)
    at removeNullItem (http://localhost:6351/_content/AntDesign.Charts/ant-design-charts-blazor.js:133:13)
    at proccessObject (http://localhost:6351/_content/AntDesign.Charts/ant-design-charts-blazor.js:124:13)
    at removeNullItem (http://localhost:6351/_content/AntDesign.Charts/ant-design-charts-blazor.js:137:9)
    at proccessObject (http://localhost:6351/_content/AntDesign.Charts/ant-design-charts-blazor.js:124:13)
    at removeNullItem (http://localhost:6351/_content/AntDesign.Charts/ant-design-charts-blazor.js:137:9)
    at proccessObject (http://localhost:6351/_content/AntDesign.Charts/ant-design-charts-blazor.js:124:13)
    at removeNullItem (http://localhost:6351/_content/AntDesign.Charts/ant-design-charts-blazor.js:137:9)
      Microsoft.JSInterop.JSException: Maximum call stack size exceeded

**Comment by violet701** [comment]
请确认 在 src/AntDesign.Charts/wwwroot/ant-design-charts-blazor.js文件中 从0.5.2版本开始 加入的chartRef是否确有必要        

经过测试，删除
create: (type, domRef, domId, chartRef, csConfig, others, jsonConfig, jsConfig) 中的chartRef

并且删除以下代码                
               plot.on('afterrender', (e) => {
                    chartRef.invokeMethodAsync('AfterChartRender')
                });

                plot.on('beforedestroy', (e) => {
                    chartRef.dispose();
                });
图形恢复正常。


不知道加入该代码的具体原因是什么，请确认是否可以删除。谢谢
@ElderJames @youcaiyouyoucai
